//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatSimulator
{
    using Microsoft.EntityFrameworkCore;
    using System;
   
    
    public partial class EsercitazioneBancaEntities : DbContext
    {
        //public EsercitazioneBancaEntities()
        //    : base("name=EsercitazioneBancaEntities")
        //{
        //}

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public EsercitazioneBancaEntities(DbContextOptions<EsercitazioneBancaEntities> options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=B80MI-SCM117;Database=EsercitazioneBanca;Trusted_Connection=True;");
        }

        public virtual DbSet<Banche> Banche { get; set; }
        public virtual DbSet<Banche_Funzionalita> Banche_Funzionalita { get; set; }
        public virtual DbSet<ContiCorrente> ContiCorrente { get; set; }
        public virtual DbSet<Funzionalita> Funzionalita { get; set; }
        public virtual DbSet<Movimenti> Movimenti { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }
    }
}
